
title: My Resume
url: 'https://c1arissa.github.io'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-4

#Profile information
name: Clarissa Podell
#tagline: Full Stack Developer
pic: orig.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: clarissapodell@gmail.com
phone: 012 345 6789
website: c1arissa.github.io #do not add http://
linkedin: clarissapodell
github: c1arissa
#twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
